HumanExposure/factotum

dashboard/fixtures/seed_product_category.yaml, dashboard/models/product_category.py, templates/data_group/datagroup_detail.html
Will require at ```python manage.py loaddata seed_product_category```
=> Puc data seed

factotum/settings.py, factotum/urls.py
Need to run
```pip install django-debug-toolbar```
to get this to work
=> adding dev-toolbar

dashboard/tests/functional_tests.py
this is the fix needed for issue `#132`
=> add StaticLiveServerTestCase to functional_tests

dashboard/tests/functional_tests.py, templates/data_group/datagroup_detail.html
this will allow the <div> that is being tested to appear in the browser
=> fix test for extract submit button

dashboard/fixtures/10_extractedchemical.yaml, dashboard/models/data_document.py, dashboard/models/product_category.py, dashboard/models/qa_group.py, dashboard/tests/functional_tests.py, dashboard/urls.py, dashboard/views/extraction_script.py, dashboard/views/qa.py, templates/qa/extracted_text_qa.html, templates/qa/extraction_script.html
For the tests to work properly, the file `0c68ab16-2065-4d9b-a8f2-e428eb192465.pdf` must be in `/media/Walmart_MSDS_1/pdf`
=> Extracted Text QA Page

dashboard/views/data_group.py
load queryset of only download scripts into the form for selection
=> only download scripts in datagroup_new dropdown

static/js/data_group_detail.js, static/js/data_group_form.js, static/js/export.js, templates/data_group/datagroup_detail.html, templates/data_group/datagroup_form.html
using `<table display:none>` method for downloading _register_records.csv_
=> use hidden table for register records template

dashboard/tests/__init__.py, dashboard/tests/loader.py, dashboard/tests/test_dashboard.py, dashboard/tests/test_models.py, dashboard/tests/test_qa.py, requirements.txt
Note that I'm using lxml as a lightweight alternative to Selenium in these tests. Everything that Selenium was being used for in the older version was HTML scraping. I added it to my environment using Anaconda. (When I tried to install it with pip I got some dependency errors; YMMV)
=> creating dashboard and qa tests

dashboard/tests/test_dashboard.py, dashboard/urls.py, dashboard/views/dashboard.py, templates/dashboard/index.html
button on dashboard to download CSV of all PUC objects.
=> download PUC CSV

dashboard/fixtures/03_datagroup.yaml, dashboard/tests/functional/test_extracted_text_upload.py, dashboard/views/data_group.py
Yes, this is intended to base onto `master`.
This looks like a lot of new code, but that's only because I have added a ton of `print()` statements to try and figure out why I'm unable to write a good test for this. I'm still working on fabricating the csv file  in memory and streaming it to the test client. 
Lines 177 and 179 are where the actual fix happens.
=> 371 HOTFIX: Repair csv extracted chemical upload

dashboard/tests/functional/test_datagroup_detail.py, templates/data_group/datagroup_detail.html
=> 326 navigate to datasource

dashboard/models/product_to_puc.py, dashboard/tests/functional/test_product_detail.py, dashboard/urls.py, dashboard/views/product_curation.py, templates/product_curation/product_detail.html, templates/product_curation/product_puc.html
While making changes to the product detail page for this ticket, I also stubbed out the additional layout Dave provided in his mock-up. I subsequently commented most of it out, to be re-introduced as we build that functionality, but I wanted the reviewer to be aware of these comments in the template.
Additionally, I attempted to add functionality to change the current puc for a product. This wasn't specifically a part of the ticket, and I haven't actually gotten it working yet. You can see that code in product_curation.py lines 137-147. Specifically, the newly chosen puc isn't actually getting assigned to the producttopuc object. It isn't generating an error or anything; it just isn't getting assigned. The other changed values to get assigned and saved, so there's something else going on. …
=> 313 puc assignment

dashboard/tests/unit/test_habits_n_practices.py, dashboard/views/data_group.py, dashboard/views/get_data.py, templates/data_group/habitsandpractices.html, templates/get_data/get_data.html
I also added the change for the default script in the `habitsandpractices` view in this ticket.
=> 351 remove product category

dashboard/tests/functional/test_datagroup_detail.py, dashboard/views/data_group.py
=> #385 redirect to datagroup detail page

dashboard/tests/functional/test_product_detail.py, dashboard/views/product_curation.py, templates/product_curation/product_puc.html
this PR resolves tickets:
#389 
#390 
I added the testing for both of these to an existing test, if needed, I could pull the assertions out into another test or two, just seemed simplest to do it this way.
=> 389 390 show puc if assigned fix bug

dashboard/tests/functional/test_datagroup.py, factotum/urls.py
this is the simplest ticket I've had to solve.
=> redirect user to login page if not logged in

dashboard/tests/functional/test_datagroup_detail.py, templates/data_group/datagroup_detail.html
this is another really simple fix. At some point we will probably want to refactor this view, cause we have been adding things to it for a while individually.
=> limit bulk create button

templates/qa/extracted_text_qa.html
I don't think this one needs a test--it was just moving a field up on a form. Tell me if you disagree!
=> moving raw central comp field

dashboard/fixtures/01_lookups.yaml, dashboard/models/data_group.py, dashboard/tests/functional/test_datagroup_create_upload.py
…nch 414; correct object pk in test file
=> Corrects object in test file

dashboard/models/data_group.py, dashboard/tests/functional/test_datagroup_create_upload.py
=> Fixed tests so all pass on dev

dashboard/fixtures/12_habits_and_practices.yaml, dashboard/fixtures/13_habits_and_practices_to_puc.yaml, dashboard/models/PUC.py, dashboard/models/extracted_habits_and_practices_to_puc.py, dashboard/tests/unit/test_models.py, dashboard/views/get_data.py, templates/get_data/get_data.html
added method to PUC model to get all other PUCs of the same gen_cat/prod_fam/prod_type to grab all associated Extracted HabitsAndPractices, and included each associated PUC into the card.
PUC terms to search to pull up seed data:
-- bubbles
-- art
-- landscape
=> 411 lower level pucs

dashboard/models/product_to_puc.py
added 2 more choices to the tuple of tuples.  I just did this cause I wanted to try editing and commiting w/in github. This is a simple enough ticket so I thought I'd give it a try. 
More might need to be added to the `Product` method `get_uber_product_to_puc` for functionality to be complete.
=> add options to classification choices

dashboard/models/product_to_puc.py
Reverts HumanExposure/factotum#501
=> Revert "add options to classification choices"

dashboard/forms.py, dashboard/tests/functional/test_datadocument_detail.py, dashboard/tests/functional/test_product_linkage.py, dashboard/views/data_group.py, dashboard/views/product_curation.py, templates/data_document/data_document_detail.html, templates/product_curation/link_product_form.html
like I said on the phone, I've added a hidden input to the form to pass which return_url the view should redirect to after saving.
Also, I noticed that the `Code Menu` on the data_group update view wasn't being loaded with data, so I added that to the view.
=> 544 create products datadocument detail

dashboard/tests/functional/test_dashboard.py, dashboard/views/dashboard.py, static/js/bubble_chart.js, templates/dashboard/index.html
this changes the value of `num_prods` in the downloaded PUC csv from the get data page to count all children of the over-arching category. It also adds a legend in the bubble chart.
=> 568 bubble hierachy

dashboard/models/script.py
See comment on already-merged code:
https://github.com/HumanExposure/factotum/commit/b5897b533a75670f0bc7b9ebc68e929b637720ad#commitcomment-31490016
=> #579 Fix handling of multiple GQ Groups

dashboard/tests/functional/test_datagroup_form.py, templates/data_group/datagroup_detail.html
=> 561 Remove ExtractionScript reference from data group detail page

.gitignore, dashboard/tests/integration/test_user_experience.py, static/css/dashboard/product.css, static/js/dashboard/product.js, templates/core/base.html, templates/product_curation/product_detail.html
#571
pretty straight forward, this will likely conflict with changes I have in the PR for issue #600 in the `product_detail.html` where I added the hyperlink to `(edit)` the PUC in admin.
=> 571 puc tag submit

dashboard/forms/forms.py, dashboard/tests/functional/test_datadocument_form.py, templates/data_document/data_document_detail.html
Added Url link to data document page and ability to edit in editing page
=> 828 show data doc url

templates/product_curation/bulk_product_tag.html
=> 684 Make product detail link open a new window

dashboard/forms/forms.py
Whew. Gonna need a nap after this one.
=> 655 Edit form label

dashboard/fixtures/05_product.yaml, dashboard/fixtures/09_productdocument.yaml, dashboard/fixtures/12_product_to_puc.yaml, dashboard/models/PUC.py, dashboard/tests/functional/test_dashboard.py, dashboard/tests/functional/test_datadocument_detail.py, dashboard/tests/functional/test_get_data.py, dashboard/tests/functional/test_product_puc.py, dashboard/views/dashboard.py, static/js/bubble_chart.js
There is a new property method on the PUC model that reports the cumulative product count. I have changed the bubble chart to use that property for the circle radius.
Testing this required adding new document-to-product and product-to-puc relationships to the seed data.
=> 866 puc bubble count

dashboard/models/data_group.py
The "upload extracted chemicals" button was not appearing because my code was incorrectly testing whether all of the data group's records had been extracted yet.
=> Correct boolean query

dashboard/tests/functional/test_datadocument_detail.py, static/js/dashboard/datadocument_detail.js, templates/data_document/chemical_card.html, templates/data_document/data_document_detail.html
=> 881 Data Document chemical name ellipsis

dashboard/models/PUC.py, dashboard/tests/integration/test_chemical_detail.py, dashboard/urls.py, dashboard/views/chemical.py
The non-formulation PUCs were being displayed in the chemical detail view. I added a test that failed under the status quo, made the fix, and confirmed that the new test passed.
=> 1337 puc fix

dashboard/tests/functional/test_qa_summary.py, dashboard/views/qa.py, templates/qa/extraction_script_summary.html
=> 1639 qa notes

templates/qa/extraction_script_index.html
1. Added Script Updated column to QA Composition Ext. Script table.
=> 1654: Add Extraction Script Date to Composition QA main page

static/js/dashboard/qa_chemical_presence_index.js, static/js/dashboard/qa_summary_table.js, templates/qa/chemical_presence_index.html
Added link to data group summary page in QA Chemical Presence table.
=> 1651: Link to Chemical Presence QA Summary Page

feedback/views/comment.py
I accidentally closed the origin PR without merging it. So opened another one to make it up.
=> 1331 comment redirect

dashboard/forms/forms.py, dashboard/tests/integration/test_qa.py
closes: #1723 
This problem was not caused by foreign key constraints, as I suspected, but just required a change in the order the formsets were saved.
=> 1723 delete chem

dashboard/tests/functional/test_datadocument_detail.py, dashboard/urls.py, dashboard/views/data_document.py, dashboard/views/product_curation.py, static/js/dashboard/bulk_product_puc.js
Removing limit makes the results take too long to load (Over 500K products, each result could be thousands). After speaking with Sakshi decide to raise it instead.
=> Change limit and pagination bulk assignment

dashboard/admin.py, dashboard/tests/functional/test_functional_use_curation.py, dashboard/tests/functional/test_nav_bar.py, dashboard/urls.py, dashboard/views/__init__.py, dashboard/views/functional_use_curation.py, static/css/dashboard/grid_list.css, static/js/dashboard/functional_use_categories.js, static/js/dashboard/functional_use_curation.js, templates/core/base.html, templates/functional_use_curation/functional_use_curation.html
Closes: #1807 
Adds an ag-grid table of distinct reported functional use + functional use category values.
=> 1807 Display distinct reported functional use+category assignments

dashboard/models/data_document.py, dashboard/tests/integration/test_browser_edits.py, dashboard/views/data_group.py, templates/data_group/data_group_tracking.html
Closes: #1831 
This adds a column to the table in `http://127.0.0.1:8000/data_group_tracking/`
=> 1831 document count in data group tracking

dashboard/models/data_document.py, dashboard/tests/integration/test_browser_edits.py, dashboard/views/data_group.py, templates/data_group/data_group_tracking.html
Reverts HumanExposure/factotum#1838. Matt and I discovered an error.
=> Revert "1831 document count in data group tracking"

factotum/urls/api.py, requirements.txt
Tested factotum API still run. All test cases are skipped now.
=> 1869: update django rest framework version

dashboard/forms/forms.py, dashboard/tests/functional/test_ajax.py, dashboard/tests/integration/test_curated_chemical_removal.py, dashboard/urls.py, dashboard/views/ajax.py, dashboard/views/chemical_curation.py, static/js/dashboard/curated_chemical_removal.js, static/js/dashboard/datadocument_detail.js, templates/chemical_curation/curated_chemical_removal_index.html, templates/core/base.html
Closes #1888 
Added page Data Curation -> Curated Chemical Removal
For performance purpose, added search by raw chem name/cas first. User has to enter at least 2 characters to narrow down the data, so that the aggregation will perform.
=> 1888: Curated Chemical Removal index page

dashboard/views/ajax.py, static/js/dashboard/curated_chemical_removal.js
Closes #1928 
Removed data association on Action column and make it non searchable/orderable.
=> 1928: fix curated chemical removal table search

dashboard/tests/functional/test_datagroup_detail.py, dashboard/views/data_group.py, static/js/dashboard/datagroup_detail.js, templates/data_group/datagroup_detail.html
=> 1915: Display PUC on Data Group Page

dashboard/tests/integration/test_chemical_detail.py, templates/chemicals/chemical_detail.html
closes #1921 
Moves the accordion out to accommodate the table.  Made some minor styling changes that I think will look good.
=> 1921 minimize keyword table

dashboard/tests/functional/test_extracted_qa.py, dashboard/urls.py, dashboard/views/qa.py, templates/qa/qa_manual_composition_index.html, templates/qa/qa_manual_composition_summary.html
=> 1887: Manual Composition QA Summary Page

dashboard/tests/integration/test_curated_chemical_removal.py, dashboard/urls.py, dashboard/views/ajax.py, dashboard/views/chemical_curation.py, static/js/dashboard/curated_chemical_detail.js, templates/chemical_curation/curated_chemical_detail.html
Closes #1936 
Created curated_chemical_detail page linked from the curated_chemical_removal count column.
=> 1936: Chemical Curation Removal Detail page

dashboard/tests/functional/test_get_data.py, dashboard/urls.py, dashboard/views/get_data.py, templates/get_data/get_data.html
Closes #1965 
Added 'Bulk Download Functional Use Data' button on the /get_data/ page to download all functional uses.
=> 1965: Bulk Download Functional Use Data

dashboard/tests/functional/test_datadocument_detail.py, dashboard/views/data_document.py, templates/data_document/data_document_detail.html
Closes #1962 
Added download button for FU type of document.
=> 1962: download chemical data for functional use documents

dashboard/tests/integration/test_browser_edits.py, dashboard/views/data_group.py, templates/data_group/data_group_tracking_edit.html
Closes #2031. Can test with http://127.0.0.1:8000/data_group_tracking/edit/6/
=> 2031 adding comp count to confirmation modal

dashboard/forms/forms.py, dashboard/models/extracted_hhrec.py, dashboard/tests/functional/test_datadocument_detail.py
Closes #2060. My last factotum ticket!
=> add chem_detected_flag to hh card form

dashboard/tests/functional/test_ajax.py, dashboard/views/ajax.py
=> 2120: handle missing extractedtext in ajax view
