- dashboard/models/data_source.py
this was fixed in Zach's initial extraction script branch, but it never made it to `dev`, so I've added it here. We can't have zero estimated records if we want to know what percent of estimated records are uploaded or registered. I've taken the liberty to add the default value of 47 because it is the most common random number. In other words, 47 appears to be the quintessential random number of the universe.
> ZeroDivisionError bug fix w/ estimated records in DataSource

- templates/dashboard/index.html
The `index.html` template was using different variable names than what `views\dashboard/py` was preparing.
> Fix dashboard cards

- dashboard/tests/functional_tests.py
change csv map to one that is there in static, the test is failing cause it's looking for a file we deleted when removing the media folder, the input NEEDs a csv to be valid
> search for existing csv, media has been removed

- dashboard/views/data_group.py
the fix here will isolate the rendering of the upload PDF form in the page until ALL pdfs are uploaded, once that is true, then the extracted text upload form will show up.
> change form logic on render

- dashboard/tests/functional_tests.py
- dashboard/views/product_curation.py
- templates/product_curation/link_product_form.html
The post-save and post-cancel redirect from the product linking page `http://127.0.0.1:8000/link_product_form/<pk>` were using the old DataSource id instead of the DataGroup id. This has been corrected
> Fix post-save and post-cancel redirect

- dashboard/models/product.py
- dashboard/tests/functional_tests_rollback.py
- dashboard/views/product_curation.py
this adds 3 new input boxes to the view. the test asserts that the default `stub_xx` value loads into the page. However we may want to isolate the creation/linking of products <-> documents, we are currently searching for a product with the same title first and assigning that if it exists.
> add inputs to link_product_form view and test

- dashboard/tests/__init__.py
- dashboard/tests/test_faceted_search.py
- dashboard/urls.py
- dashboard/views/__init__.py
- dashboard/views/dsstox_substance.py
- dashboard/views/search_forms.py
- templates/chemicals/dsstox_substance_detail.html
The `/find` page now explicitly filters on results whose `facet_model_name` is either "Data Document" or "Product". 
I also added a few new files: before I excluded those models from the search results page, it was throwing errors related to the lack of a view to handle the URLs for DSSTox Substance objects.
> Exclude DSSToxSubstance and ExtractedChemical from the search results

- dashboard/tests/functional/test_datagroup_detail.py
- dashboard/views/data_group.py
- dashboard/views/product_curation.py
- templates/data_group/datagroup_detail.html
currently the button that is in the 'Product' column will be filled with the title of the product, which if bulk-created will end up being 'unknown' for potentially many of the rows in this table. Probably not a big deal, but worth mentioning.
> move bulk button, add product column w/ link

- dashboard/tests/functional/test_chem_search.py
- dashboard/tests/functional/test_product_linkage.py
- dashboard/views/product_curation.py
I didn't want to mess with seed data for this small fix. To see it in action on dev, replicate the test:
1. In the admin console, update datagroup "Walmart MSDS 1" (pk=17) to have the Group Type "composition" (group_type_id = 2)
2. Go to /link_product_form/129298 (datadocument 129298 belongs to the datagroup updated in step 1)
3. Verify that the Document Type dropdown contains only the 4 document_type options associated with the "composition" group type (group_type_id=2)
> filtering document_type dropdown on product linkage form

- dashboard/search_indexes.py
There are no tests for this - it's just an attempt to prepare for future search applications by reducing the amount of ngram-searching that's done. Fields that should not be searched in a "fuzzy" fashion, like the CAS numbers or filenames, are now CharField types in the search index.
> 372 fix indexing methods

- dashboard/tests/functional/test_extracted_qa.py
a test added for a fix we implemented a while ago. all you should need to do to check this out is run the tests.
> test user redirected to /qa/ after last extext record approved

- dashboard/fixtures/02_datasource.yaml
- dashboard/fixtures/03_datagroup.yaml
- dashboard/fixtures/06_datadocument.yaml
- dashboard/fixtures/07_script.yaml
- dashboard/fixtures/08_extractedtext.yaml
- dashboard/fixtures/10_extractedchemical.yaml
- dashboard/fixtures/15_extractedfunctionaluse.yaml
- dashboard/fixtures/load_fixtures.sh
- dashboard/tests/functional/test_qa_seed_data.py
- dashboard/views/extraction_script.py
- templates/qa/extracted_text_qa.html
- templates/qa/extraction_script.html
The `extracted_text_qa.html` template now checks to see if the data document belongs to a data group whose group type is "Functional use." If it is not, then the template includes the fields specified in the ticket. Otherwise, it does not render those fields. 
The seed data yaml files now include an Extraction Script, a Data Group, a DataDocument, and two new ExtractedChemical records. I also added an ExtractedFunctionalUse object, but it's not used here.
There are two different test classes for the QA page. I modified the one that uses the seed data for testing this issue, and renamed it to clarify why we have two files. 
I'm not entirely happy with this check in the template:
`{% if doc.data_group.group_type.title != "Functional use" %} `
I don't like hardcoding the case-sensitive title …
> 418 Conditional field display in QA page

- requirements.txt
Both of the packages that broke as a result of the Django 2.1 changes have been updated and can be automatically updated with pip.
Run `pip install --upgrade -r requirements.txt`
> Update requirements.txt to use compatible versions of widgets

- dashboard/tests/functional/test_faceted_search.py
- dashboard/views/search.py
#199
returns all `products` now, check `/find/?q=insecticide`
> #199 override get_queryset for size option

- dashboard/tests/functional/test_datadocument_detail.py
- dashboard/views/data_document.py
- dashboard/views/data_group.py
- templates/data_document/data_document_detail.html
This branch satisfies the terms of ticket #470 : the data document detail page opens whether or not the data document has an associated ExtractedText object, and the test checkes every DataDocument object in the seed data.
There may be other cases where the code still expects an ExtractedText object and fails when one is absent, but I have not yet encountered them. The data group detail page, for example, loads fine. The QA pages are centered around the ExtractedText model rather than the DataDocument model.
> Ticket 470: Handle absent extracted text

- templates/qa/extracted_text_qa.html
The tag that generated the pdf link on the QA page was using obsolete code. It has been updated.
> 509: Repair pdf link in Extracted Text QA page

- dashboard/tests/functional/test_product_detail.py
- templates/product_curation/product_detail.html
could have removed the category labels if no PUC, but i chose to keep them in place, would be easy enough to not show them if that's preferred
> #474 reconfigure div with puc info

- dashboard/search_indexes.py
- dashboard/tests/functional/test_faceted_search.py
- templates/search/facet_search.html
- templates/search/indexes/dashboard/product_text.txt
The elasticsearch index now includes the Product.upc field as its own column. We discussed changing the tabular format back to a series of divs, but as of commit e913058, the template still uses a table with a column for each returned field.
> #521 Search results now include Product.upc field

- dashboard/models/qa_group.py
- dashboard/models/script.py
- dashboard/tests/functional/test_qa_seed_data.py
- dashboard/tests/integration/test_user_experience.py
- dashboard/views/extraction_script.py
- templates/qa/qa_index.html
This ticket began as a bug fix when users noticed multiple QA Group records had been created for the same Script object. The presence of multiple QA Group records caused an error when users tried to open the QA page for a Script. 
In this branch, the creation of a QA Group is now handled by a method in the Script model. The QA Group can be created from either the Data Document Detail page (the "QA" link will create a QA group for the document's Extraction Script if one does not exist) or from the QA page (via the "Begin QA" button). 
If the user opens the Extracted Text object's QA page and it does not already belong to the QA group for its related Script, the Extracted Text object is assigned to the existing QA Group. 
The QA index page no longer shows a link to the Script's QA page if …
> 579 Refine QA Group creation workflow

- dashboard/tests/functional/test_extracted_text_upload.py
- dashboard/views/data_group.py
this is the simplest way I could think of to check that each record for a given `data_document_id` has the same value for `prod_name`. The error was being thrown because there ended up being ~224 `ExtractedChemical` cards on the QA page, each card has something like 7 `<input>` fields and Django has a default setting of a max number of 1000. 
This seems to be a unique case w/ this group of datadocuments, but to resolve @kdionisio and I thought it would be best to make sure the `data_document_id` and `prod_name` fields are the same. The picture I attached to the issue might help illustrate.
I also added to an existing test that an error will be thrown in this event. A thing to note was that I removed the `08_extractedtext.yaml`. With that being loaded into the test I realized that the test …
> verify prod_name is the same for every data_document

- dashboard/tests/functional/test_qa_seed_data.py
- templates/qa/extracted_text_qa.html
Quick ticket: added a link to the QA detail page, wrote a test to make sure it's there.
> 532: Extracted Text QA page now links to its Data Document Detail page

- dashboard/fixtures/03_datagroup.yaml
- dashboard/fixtures/06_datadocument.yaml
- dashboard/fixtures/08_extractedtext.yaml
- dashboard/models/product_document.py
- dashboard/tests/functional/test_datagroup_detail.py
- dashboard/tests/functional/test_product_linkage.py
- dashboard/views/data_group.py
Change "Walmart MSDS 3" data group in seed data to Composition type; correct"extracted" status for a data document in data group 6; add a prod_name to an extractedtext record for testing; enhance str output of ProductDocument object; update existing loader-only bulk creation test; add extensive tests for bulk creation with seed data
> #530 Changes to the naming of products during bulk creation, heavy-duty testing

- dashboard/forms.py
- dashboard/tests/functional/test_qa_seed_data.py
this is a 1 character bug fix!
the child inline formset will now default to 1 extra form which was originally the case, but when we had added this to the datadocument detail view, we had not wanted to add the extra form, no longer the case.
there are 2 errors in the tests which I think have already been resolved, but are not merged to `dev` yet from wilson's ticket
> add extra child form, test

- dashboard/models/data_group.py
- dashboard/tests/functional/test_datagroup_form.py
- dashboard/views/data_group.py
#538
Ended up doing a belt-and-suspenders approach here, where I disable the form field as the ticket indicates, but also add a clean_fields() validation that works on the admin side, or also if someone bypasses the disabled field on the user side.
> 538 prevent datagroup type from being changed once extracted docs exist

- dashboard/forms.py
- dashboard/tests/integration/test_user_experience.py
- dashboard/views/extraction_script.py
I solved this by adding a new `exclude` parameter to the `create_detail_formset()`method. Now when you call that method from a view, you can specify certain fields to be excluded from the rendered form.
> #591 remove weight fraction type from QA view

- dashboard/tests/functional/test_datagroup_detail.py
- dashboard/views/data_group.py
- dashboard/views/product_curation.py
The numeric UPC index was previously generated by counting Product records and incrementing the count by one. This caused errors when a Product had been deleted, since the new index number matched a previously created one.
> #765 HOTFIX change stub upc generation

- requirements.txt
- templates/data_document/data_document_detail.html
I added `ipython` to the requirements here so I don't have to install it separately like I have been. I find it hard to believe that anyone is using the `manage.py shell` w/o it, but that may be the case.
> #988 change icon

- dashboard/tests/functional/test_qa_seed_data.py
- dashboard/tests/functional/test_qa_summary.py
- dashboard/views/qa.py
1. For CP QA page, filter out datagroup that has no extracted texts.
> 1649: Remove Empty Data Groups from CP QA

- templates/qa/extraction_script_index.html
closes #1654 
The datatable was sorting by displayed text (e.g., Apr 04, 2020) . Added data-order to sort by date in yyyy-mm-dd format.
> 1654: sort date by yyyy-mm-dd format

- static/js/dashboard/product_delete.js
- templates/data_group/product_delete_progress.html
1. After delete products task done, delete it. Otherwise, data group detail page will keep polling tasks and cause UI error in console log.
2. To test, verify that after the task is done and re-direct to data group detail page, no browser console error occurs.
> 1626: delete task after done

- dashboard/models/script.py
- dashboard/views/qa.py
- templates/qa/extraction_script_index.html
I corrected the calculations on script.py, however the calculations in that file are in my opinion not necessary. The percent of QA documents checked is already calculated in the view in order to display it in the "Percent QA Checked" column, the template already has an if/else conditional so we could simply use that conditional to choose what text is displayed as well along with the style of the button. Chose to correct the calculations in case that file serves another purpose or if was done that way to future proof something (couldn't find any other portion of the code using it though). I would also change the return from a string to something more useful.
> Correct QA Status Calculations

- dashboard/views/qa.py
- templates/qa/extraction_script_index.html
As I mentioned in merge request:
https://github.com/HumanExposure/factotum/pull/1750
I believe the calculations in that file(script.py) are in my opinion not necessary. It took me a while to find, but that was the cause for the repeated 380+ queries, even though the info was already available in the qa.py view. I got rid of the reference to that file in the template and just used the info already available from qa.py. That part of the code in script.py is now not been used at all (or so I believe). Left it, in case I am wrong.
> Remove unnecessary calculation from script.py

- dashboard/tests/functional/test_datadocument_detail.py
- dashboard/tests/functional/test_qa_seed_data.py
- dashboard/urls.py
- dashboard/views/data_document.py
- dashboard/views/qa.py
- templates/core/base.html
- templates/qa/extraction_script_index.html
1. Modified current /compextractionscript endpoint to accept group_type parameter, so we can re-use the views/templates. For Functional use page, use ?group_type=FU.
2. For existing Composition Ext. Script page, Sakshi agreed to show CO type only
To test:
Go to QA -> Functional Use - Ext. Script page.
> 1777: functional use extraction script QA page

- dashboard/tests/integration/test_browser_edits.py
- dashboard/tests/integration/test_data_document_detail.py
- static/js/dashboard/data_group_tracking.js
- templates/data_group/data_group_tracking.html
Added search per column in data group tracking table.
To test, go to Data Curation -> Data Group Tracking page, use can filter by curation step status. The search is cumulative.
> 1811: search data group tracking table by column value

- dashboard/admin.py
- dashboard/tests/integration/test_puc_detail.py
- static/js/dashboard/puc_detail.js
- templates/puc/puc_detail.html
closes #1826 
Fires a click event on each panel when the associated anchor is clicked.
This is somewhat unnecessary, but the table only loads on each click in an attempt to lighten the page's load.  Rather than abstract logic out to separate the "click" and "load" functionality, it's much easier just to fire a click event.
> 1826 puc table link

- dashboard/fixtures/12_product_to_puc.yaml
- dashboard/tests/integration/test_chemical_detail.py
- dashboard/views/ajax.py
Closes: #1785 
This adds a test to confirm that the changes in #1282 corrected the Products shown when the user filters the chemical detail page on a PUC. It also includes a fix to the documents table on that page. 
The tables previously failed to respect the uberpuc assignments - when the AJAX query returned a set of products filtered by a PUC, the PUC was arbitrarily chosen from among all the PUCs assigned to the product. Now it uses the uberpuc selection logic. 
To reproduce the now-fixed error on the Documents table:
*On a branch other than this one,* and with the production data loaded, open the chemical detail page for Formaldehyde: `http://127.0.0.1:8000/chemical/DTXSID7020637/`
Click the filter button next to "Personal Care" to filter by that PUC. The number of Documents and …
> 1785 Add test for PUC filtering on chemical detail page

- dashboard/fixtures/18_functional_use.yaml
- dashboard/tests/functional/test_chemical_detail.py
- dashboard/tests/functional/test_functional_use_curation.py
- dashboard/tests/integration/test_chemical_detail.py
- dashboard/urls.py
- dashboard/views/chemical.py
- static/js/dashboard/chemical_detail.js
- templates/chemicals/chemical_detail.html
1. This PR covers ticket #1830, #1827 and #1852
2. Verify functional uses table is added to chemical detail page and can be filtered by PUC.
To Do: add link to functional use category page once #1825 is done.
Sample page:
http://localhost:8000/chemical/DTXSID6026296/
> Add table divider and functional uses table in chemical detail page

- dashboard/admin.py
The product count columns have been removed. There appear to be no tests that involved those values.
> 1848 fix PUC admin

- dashboard/forms/forms.py
- dashboard/tests/functional/test_extracted_qa.py
- dashboard/tests/functional/test_nav_bar.py
- dashboard/urls.py
- dashboard/views/qa.py
- static/js/dashboard/qa_manual_composition_index.js
- templates/core/base.html
- templates/qa/qa_manual_composition_index.html
closes: #1885 
The seed data does not include manually-extracted composition records, so I used a factory to create them in my test. If you want to add them to your local dev environment, this code from the test should work in the shell:
```{python}
from dashboard.tests import factories
from dashboard.models import (
ExtractedText,
Script,
DataGroup,
)
script = Script.objects.filter(title="Manual (dummy)", script_type="EX").first()
dgs = DataGroup.objects.filter(group_type__code="CO")
for dg in dgs:
doc_count = ExtractedText.objects.filter(
data_document__data_group=dg
).count()
factory_count = (doc_count // 2) + 1
extext = factories.ExtractedTextFactory.create_batch(
factory_count,
data_document__data_group=dg,
extraction_script=script,
data_document__title=f"{dg.name} manually extracted …
```
> 1885 QA index page for manually extracted composition docs

- .gitignore
- dashboard/migrations/0191_drop_auditlog_extracted_text_fk.py
- dashboard/tasks.py
- dashboard/tests/functional/test_auditlog.py
- dashboard/tests/unit/test_tasks.py
There was a bug where if more than one dsstox id was returned found, the record would not be provisioned.
A `.distinct()` was added to change this to requiring more than one different dsstox id.
Also dropped the auditlog extracted_text_id foreign key constraint. There are rows in production rawchem table whose extracted_text_id that does not exists in extractedtext table, which is wrong. This caused error throw when set the provisional sid. Drop the constraint is auditlog is fine as this is audit trail anyway. But how the production database get into this state is still unknown/unresolved.
> Hotfix Provisional DTXSID Assignment

- dashboard/fixtures/07d_rawchem.yaml
- dashboard/forms/forms.py
- dashboard/tests/integration/test_curated_chemical_removal.py
Closes: #1937 
Not much was needed here. The `provisional` flag is now set to `False` when the `RemoveCuratedChemicalLinkageForm` on the `/curated_chemical_removal/` page does its thing. 
Note that this form's `save(self)` method is the only place the `provisional` field is synced with curation removal. If some other function uses the ORM or a database query to uncurate a `RawChem` record by setting the `dsstox` value to `None`, the flag will not be reset.
> 1937: remove provisional flag with curation break

- dashboard/tests/functional/test_functional_use_curation.py
- dashboard/tests/integration/test_chemical_detail.py
- dashboard/tests/integration/test_functional_use_curation.py
- dashboard/urls.py
- dashboard/views/functional_use_curation.py
- static/js/dashboard/functional_use_curation.js
- templates/functional_use_curation/functional_use_curation.html
Closes #1941 
Added button to remove reported functional uses with no chemical on /functional_use_curation/ page.
> 1941: remove empty Reported Functional Uses from curation page

- docker/docker-compose.override.yaml
- template.env
Closes #2042 
Add `COMPOSE_PROJECT_NAME=factotum` to .env will make all services has `factotum_` prefix.
The container name for pretty self-explained:
1. factotum_factotum: the factotum web application
2. factotum_factotum-ws: the factotum web services API application
3. factotum_nginx: the nginx proxy to serve factotum and factotum-ws
4. factotum_celery: the celery task worker service
5. factotum_celery-beat: the celery beat service for scheduled tasks
6. factotum_redis: the redis host used by django and celery
7. factotum_elasticsearch: the elastic search host
8. factotum_logstash: the logstash host to feed data to elastic
> 2042: update container names

- dashboard/tests/functional/test_search.py
- dashboard/views/search.py
- elastic/search.py
Closes: #2005 
Special characters in query terms are now escaped before they are sent to the elasticsearch server. See the original ticket for examples.
I have refactored the functional tests into a new class that passes a factory-built request to the `search_model` view rather than using the test client. This helps avoid just reproducing a bunch of string-encoding logic inside the test.
> 2005 escape search characters

- dashboard/tests/functional/test_auditlog.py
- dashboard/tests/functional/test_dashboard.py
- dashboard/tests/functional/test_datadocument_detail.py
- dashboard/tests/functional/test_extracted_text_upload.py
- dashboard/tests/functional/test_product_csv_upload.py
- dashboard/tests/functional/test_product_detail.py
- dashboard/views/ajax.py
- dashboard/views/dashboard.py
Closes: #2118 
Simple ticket - this just adds the ID column to the PUC download. I have also added a tag to several tests that fail when the entire suite is run but pass when they are run in isolation. 
```
python manage.py test dashboard.tests.functional
```
Fails.
```
python manage.py test dashboard.tests.functional --exclude-tag=fails_in_suite
python manage.py test dashboard.tests.functional --tag=fails_in_suite
```
Works
> 2118 Add PUC ID to download
